language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - cd ${TRAVIS_BUILD_DIR} && cmake ..
  - make
  - cd tests
  - ./test_all
