language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - sudo apt-get install catch

script:
  - cd build
  - cd tests
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j2 ./test_all
