language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - cd tests
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j2 ./test_all
