language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - sudo apt-get install catch

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd tests
  - ./test_all
