language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - cmake .
  - cmake --build . -- -j2
  - ls
  - cd tests
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j2 ./test_all
