language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
  - git clone https://github.com/catchorg/Catch2.git
  - cd Catch2
  - cmake -Bbuild -H. -DBUILD_TESTING=OFF
  - sudo cmake --build build/ --target install

script:
  - cmake .
  - cmake --build . -- -j2
