language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

install:
  - git clone https://github.com/catchorg/Catch2.git
  - cd Catch2
  - cmake -Bbuild -H. _DBUILD_TESTING=OFF
  - sudo cmake --build build/ --target install

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - cd tests
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j2 ./test_all
