language: cpp
compiler: gcc
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - cmake . -B build
  - cmake --build build -- -j2
  - cd build/tests
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j2 ./test_all
